name: Publish to GH Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          submodules: recursive # Ensure submodules are checked out

      - name: Setup Hugo
        run: |
          curl -L -o /tmp/hugo.tar.gz 'https://github.com/gohugoio/hugo/releases/download/v0.110.0/hugo_extended_0.110.0_linux-amd64.tar.gz'
          tar -C ${RUNNER_TEMP} -zxvf /tmp/hugo.tar.gz hugo

      - name: Build
        run: ${RUNNER_TEMP}/hugo

      - name: Checkout destination
        if: github.ref == 'refs/heads/main'
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: built-site

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          cp -R public/* built-site/
          cd built-site
          git config user.name 'dhij'
          git config user.email 'davidhwang.ij@gmail.com'
          git add .
          git commit -m 'Updated site'
          git push origin gh-pages
